[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet restore VehicleLookup.csproj",
  "dotnet publish VehicleLookup.csproj -c Release -o /app"
]

[start]
cmd = "dotnet /app/VehicleLookup.dll"

